// userAuth actions
const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL';
const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
const FETCH_USER_DETAIL_FAILURE = 'FETCH_USER_DETAIL_FAILURE';

// post actions
const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
const REFRESH_POSTS = 'REFRESH_POSTS';


export {
    // userAuth actions
    FETCH_USER_DETAIL,
    FETCH_USER_DETAIL_SUCCESS,
    FETCH_USER_DETAIL_FAILURE,
    // post actions
    FETCH_POSTS, FETCH_POSTS_SUCCESS, 
    FETCH_POSTS_FAILURE, 
    REFRESH_POSTS, 
}; 